import React from 'react'
import '../css/shareScreen.css'

function ShareToUser({ toggleShareScreen }) {
  return (
    <div className='modal'>
        <div className='overlay'>
            <div className='modal-content'>
                <div style={{display: 'flex'}}>
                    <p style={{justifyContent: 'center', padding: '0px',marginLeft: 'auto'}} onClick={()=>toggleShareScreen()}>❌</p>
                </div>
                <div className='test'><br/>
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO
                </div>
            </div>
        </div>
    </div>
  )
}

export default ShareToUser